services:
  postgres:
    image: postgres:18.1
    container_name: ecommerce-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.4
    container_name: ecommerce-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data

  lgtm:
    image: grafana/otel-lgtm:0.34.0
    container_name: ecommerce-otel-lgtm
    restart: unless-stopped
    init: true
    ports:
      - "3300:3000"
      - "3200:3200"
      - "4040:4040"
      - "4317:4317"
      - "4318:4318"
      - "9090:9090"
    environment:
      - CONTAINER_RUNTIME=docker
      - OTEL_COLLECTOR_DEBUG_EXPORTER=${OTEL_COLLECTOR_DEBUG_EXPORTER:-}
    env_file:
      - .env
    volumes:
      - lgtm_grafana:/data/grafana
      - lgtm_prometheus:/data/prometheus
      - lgtm_loki:/data/loki
      - lgtm_tempo:/data/tempo
      - lgtm_pyroscope:/data/pyroscope

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  lgtm_grafana:
    driver: local
  lgtm_prometheus:
    driver: local
  lgtm_loki:
    driver: local
  lgtm_tempo:
    driver: local
  lgtm_pyroscope:
    driver: local
