# Master password, generated by Terraform. Characters are limited to what RDS accepts.
resource "random_password" "master" {
  length  = 32
  special = false
}

# Connection details for the backend, read by External Secrets.
# The keys match the Vault secret/db keys used on the homelab.
resource "aws_secretsmanager_secret" "db" {
  name        = "/${var.project_name}/${var.environment}/db"
  description = "Postgres connection details for the backend"

  # The stack is destroyed every session. Without this, the name stays reserved for 7 days
  # after deletion and the next apply fails with "already scheduled for deletion".
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id = aws_secretsmanager_secret.db.id

  secret_string = jsonencode({
    "db-host"     = module.db.db_instance_address
    "db-port"     = tostring(module.db.db_instance_port)
    "db-user"     = var.username
    "db-pass"     = random_password.master.result
    "db-database" = var.db_name
  })
}
